export default {
  "login": "Login",
  "reset-password": "Atur Ulang Kata Sandi",
  "mail-confirm": "Periksa Email Anda",
  "change-password": "Ubah Kata Sandi",
  "success-change-password": "Kata Sandi Berhasil Diubah",
  "dashboard": "Dasbor",
  "ess": "ESS",
  "ess-leave": "Cuti ESS",
  "ess-okr": "OKR ESS",
  "ess-organization": "Organisasi ESS",
  "ess-assessment": "Penilaian ESS",
  "ess-overtime": "Lembur ESS",
  "ess-offboarding": "Offboarding ESS",
  "employee-management": "Daftar Karyawan",
  "employee-management-add": "Tambah Karyawan",
  "employee-management-detail": "Detail Karyawan",
  "employee-management-edit": "Edit Karyawan",
  "org-structure": "Struktur Organisasi",
  "org-structure-edit": "Edit Struktur Organisasi",
  "org-position": "Posisi Jabatan",
  "org-teams": "Tim",
  "org-job-level": "Level Jabatan",
  "org-department": "Daftar Departemen",
  "offboarding": "Daftar Offboarding",
  "offboarding-detail": "Detail Offboarding",
  "offboarding-salary-adjustment": "Penyesuaian Gaji Offboarding",
  "attendance-tracker": "Daftar Kehadiran",
  "attendance-tracker-add": "Tambah Kehadiran",
  "attendance-tracker-detail": "Detail Kehadiran",
  "leave-request": "Daftar Permintaan Cuti",
  "leave-request-add": "Ajukan Cuti",
  "leave-request-edit": "Edit Permintaan Cuti",
  "overtime": "Lembur",
  "payroll-list": "Daftar Payrun",
  "payroll-detail": "Detail Payrun",
  "payroll-edit": "Edit Payrun",
  "payroll-request": "Permintaan Akses",
  "self-assessment": "Daftar Penilaian Diri",
  "self-assessment-add": "Tambah Penilaian Diri",
  "self-assessment-period": "Penilaian per Periode/Karyawan",
  "self-assessment-edit": "Edit Penilaian Diri",
  "supervisor-assessment": "Daftar Penilaian Atasan",
  "supervisor-assessment-detail": "Detail Penilaian Atasan",
  "okr": "Daftar OKR",
  "okr-detail": "Detail OKR",
  "kpi": "KPI",
  "access-control": "Daftar Kontrol Akses",
  "access-control-add": "Tambah Akses",
  "access-control-detail": "Detail Akses",
  "company-profile": "Profil Perusahaan",
  "company-profile-edit": "Edit Profil Perusahaan",
  "company-branch": "Daftar Cabang",
  "company-branch-add": "Tambah Cabang",
  "company-branch-edit": "Edit Cabang",
  "attendance-config": "Konfigurasi Kehadiran",
  "attendance-config-edit": "Edit Konfigurasi Kehadiran",
  "overtime-config": "Konfigurasi Lembur",
  "overtime-config-edit": "Edit Konfigurasi Lembur",
  "holiday": "Kehadiran Hari Libur",
  "leave-management": "Konfigurasi Cuti",
  "leave-management-add": "Tambah Tipe Cuti",
  "leave-management-edit": "Edit Tipe Cuti",
  "form-template": "Daftar Template Formulir",
  "form-template-add": "Tambah Template Formulir",
  "form-template-edit": "Edit Template Formulir",
  "form-template-detail": "Detail Template Formulir",
  "form-template-supervisor": "Template Penilaian Atasan",
  "salary-base": "Gaji Pokok",
  "salary-allowance": "Tunjangan",
  "salary-deduction": "Potongan",
  "competencies": "Daftar Kompetensi",
  "competencies-detail": "Detail Kompetensi",
  "assessment-score": "Batas Nilai Penilaian"
}
