export default {
  "mobile-splash": "Mobile: Splash",
  "mobile-login": "Mobile: Masuk",
  "mobile-reset-password": "Mobile: Reset Password",
  "mobile-reset-password-check-email": "Mobile: Periksa Email",
  "mobile-create-password": "Mobile: Buat Kata Sandi",
  "mobile-reset-password-success": "Mobile: Kata Sandi Berhasil Diatur Ulang",
  "mobile-dashboard": "Mobile: Beranda (Dashboard)",
  "mobile-performance": "Mobile: Kinerja",
  "mobile-leave-request": "Mobile: Permintaan Cuti",
  "mobile-inbox": "Mobile: Kotak Masuk",
  "mobile-profile": "Mobile: Profil",
  "mobile-profile-detail": "Mobile: Detail Profil",
  "mobile-profile-edit": "Mobile: Edit Profil",
  "mobile-attendance": "Mobile: Kehadiran & Lembur",
  "mobile-location-confirmed": "Mobile: Lokasi Terkonfirmasi",
  "mobile-face-registration": "Mobile: Registrasi Wajah",
  "mobile-face-verification": "Mobile: Verifikasi Wajah",
  "mobile-attendance-form": "Mobile: Formulir Kehadiran",
  "mobile-attendance-edit": "Mobile: Edit Kehadiran",
  "mobile-leave-request-form": "Mobile: Permintaan Cuti Baru",
  "mobile-leave-detail": "Mobile: Detail Cuti",
  "mobile-overtime-request": "Mobile: Permintaan Lembur",
  "mobile-overtime-edit": "Mobile: Edit Lembur",
  "mobile-payslip": "Mobile: Slip Gaji",
  "mobile-payslip-view-request": "Mobile: Permintaan Lihat Slip Gaji",
  "mobile-payslip-view": "Mobile: Lihat Slip Gaji",
  "mobile-payslip-print-request": "Mobile: Permintaan Cetak Slip Gaji",
  "mobile-payslip-print-submitted": "Mobile: Permintaan Cetak Terkirim",
  "mobile-self-assessment": "Mobile: Penilaian Diri",
  "mobile-assessment-form": "Mobile: Formulir Penilaian",
  "mobile-manager-assessment": "Mobile: Penilaian Manajer",
  "mobile-assessment-manager-form": "Mobile: Formulir Penilaian Manajer",
  "mobile-supervisor-assessment": "Mobile: Penilaian Atasan",
  "mobile-supervisor-assessment-detail": "Mobile: Detail Penilaian Atasan",
  "mobile-supervisor-assessment-form": "Mobile: Formulir Penilaian Atasan",
  "mobile-supervisor-assessment-schedule": "Mobile: Jadwal Penilaian Atasan",
  "mobile-okr-list": "Mobile: Daftar OKR",
  "mobile-okr": "Mobile: Detail OKR",
  "mobile-okr-key-result": "Mobile: Key Result OKR",
  "mobile-offboarding": "Mobile: Offboarding",
  "mobile-exit-form": "Mobile: Formulir Keluar",
  "mobile-exit-schedule": "Mobile: Jadwal Wawancara Keluar",
  "mobile-work-handover": "Mobile: Serah Terima Pekerjaan",
  "mobile-document-handover": "Mobile: Serah Terima Dokumen",
  "mobile-responsibility-handover": "Mobile: Serah Terima Tanggung Jawab"
}
