export default {
  "login": "Login",
  "reset-password": "Reset Password",
  "mail-confirm": "Check Your Email",
  "change-password": "Change Password",
  "success-change-password": "Password Changed",
  "dashboard": "Dashboard",
  "ess": "ESS",
  "ess-leave": "ESS Leave",
  "ess-okr": "ESS OKR",
  "ess-organization": "ESS Organization",
  "ess-assessment": "ESS Assessment",
  "ess-overtime": "ESS Overtime",
  "ess-business-trip": "ESS Business Trip",
  "ess-offboarding": "ESS Offboarding",
  "employee-management": "Employee List",
  "employee-management-add": "Add Employee",
  "employee-management-detail": "Employee Detail",
  "employee-management-edit": "Edit Employee",
  "org-structure": "Organization Structure",
  "org-structure-edit": "Edit Organization Structure",
  "org-position": "Job Positions",
  "org-teams": "Teams",
  "org-job-level": "Job Levels",
  "org-department": "Department List",
  "offboarding": "Offboarding List",
  "offboarding-detail": "Offboarding Detail",
  "offboarding-salary-adjustment": "Offboarding Salary Adjustment",
  "attendance-tracker": "Attendance List",
  "attendance-tracker-add": "Add Attendance",
  "attendance-tracker-detail": "Attendance Detail",
  "leave-request": "Leave Request List",
  "leave-request-add": "Request Leave",
  "leave-request-edit": "Edit Leave Request",
  "overtime": "Overtime",
  "business-trip": "Business Trip",
  "payroll-list": "Payrun List",
  "payroll-detail": "Payrun Detail",
  "payroll-edit": "Edit Payrun",
  "payroll-request": "Request Access",
  "self-assessment": "Self Assessment List",
  "self-assessment-add": "Add Self Assessment",
  "self-assessment-period": "Assessment by Period/Employee",
  "self-assessment-edit": "Edit Self Assessment",
  "supervisor-assessment": "Supervisor Assessment List",
  "supervisor-assessment-detail": "Supervisor Assessment Detail",
  "okr": "OKR List",
  "okr-detail": "OKR Detail",
  "kpi": "KPI",
  "access-control": "Access Control List",
  "access-control-add": "Add Access",
  "access-control-detail": "Access Detail",
  "company-profile": "Company Profile",
  "company-profile-edit": "Edit Company Profile",
  "company-branch": "Branch List",
  "company-branch-add": "Add Branch",
  "company-branch-edit": "Edit Branch",
  "attendance-config": "Attendance Configuration",
  "attendance-config-edit": "Edit Attendance Config",
  "overtime-config": "Overtime Configuration",
  "overtime-config-edit": "Edit Overtime Config",
  "holiday": "Holiday Attendance",
  "leave-management": "Leave Configuration",
  "leave-management-add": "Add Leave Type",
  "leave-management-edit": "Edit Leave Type",
  "form-template": "Form Template List",
  "form-template-add": "Add Form Template",
  "form-template-edit": "Edit Form Template",
  "form-template-detail": "Form Template Detail",
  "form-template-supervisor": "Supervisor Assessment Template",
  "salary-base": "Base Salary",
  "salary-allowance": "Allowance",
  "salary-deduction": "Deduction",
  "competencies": "Competencies List",
  "competencies-detail": "Competency Detail",
  "assessment-score": "Assessment Score Threshold"
}
