export default {
  "mobile-sign-in": "Mobile: Sign in",
  "mobile-reset-password": "Mobile: Reset password",
  "mobile-clock-in": "Mobile: Clock in",
  "mobile-clock-out": "Mobile: Clock out",
  "mobile-request-leave": "Mobile: Request leave",
  "mobile-request-overtime": "Mobile: Request overtime",
  "mobile-view-payslip": "Mobile: View payslip",
  "mobile-self-assessment": "Mobile: Self assessment",
  "mobile-okr": "Mobile: OKR",
  "mobile-approve-inbox": "Mobile: Approve inbox item",
  "mobile-edit-profile": "Mobile: Edit profile",
  "mobile-offboarding-handover": "Mobile: Offboarding handover",
  "login": "Log in",
  "reset-password": "Reset forgotten password",
  "change-password": "Change password (first login)",
  "dashboard-pending": "View and act on pending items",
  "dashboard-analytics": "View analytics",
  "dashboard-offboarding": "Manage offboarding from dashboard",
  "add-employee": "Add employee",
  "edit-employee": "Edit employee",
  "view-employee": "View employee profile",
  "org-structure": "Manage organization structure",
  "start-offboarding": "Start offboarding",
  "salary-adjustment": "Process salary adjustment",
  "record-attendance": "Record attendance",
  "request-leave": "Request leave",
  "request-business-trip": "Request a business trip",
  "edit-leave": "Edit or cancel leave request",
  "request-overtime": "Request overtime",
  "approve-business-trip": "Approve or reject a business trip",
  "approve-attendance": "Approve or reject attendance or leave",
  "view-payrun": "View payrun list and details",
  "process-payrun": "Process payrun",
  "payroll-access": "Request payroll access",
  "self-assessment": "Complete self assessment",
  "supervisor-assessment": "Complete supervisor assessment",
  "okr": "Create or update OKR",
  "kpi": "Manage KPI",
  "access-control": "Add or edit user access",
  "company-profile": "Edit company profile",
  "attendance-config": "Configure attendance settings",
  "leave-config": "Configure leave types",
  "salary-config": "Configure salary components",
  "ess-home": "Use ESS as employee"
}
