export default {
  "mobile-splash": "Mobile: Splash",
  "mobile-login": "Mobile: Login",
  "mobile-reset-password": "Mobile: Reset Password",
  "mobile-reset-password-check-email": "Mobile: Check Email",
  "mobile-create-password": "Mobile: Create Password",
  "mobile-reset-password-success": "Mobile: Password Reset Success",
  "mobile-dashboard": "Mobile: Home (Dashboard)",
  "mobile-performance": "Mobile: Performance",
  "mobile-leave-request": "Mobile: Leave Request",
  "mobile-inbox": "Mobile: Inbox",
  "mobile-profile": "Mobile: Profile",
  "mobile-profile-detail": "Mobile: Profile Detail",
  "mobile-profile-edit": "Mobile: Edit Profile",
  "mobile-attendance": "Mobile: Attendance & Overtime",
  "mobile-location-confirmed": "Mobile: Location Confirmed",
  "mobile-face-registration": "Mobile: Face Registration",
  "mobile-face-verification": "Mobile: Face Verification",
  "mobile-attendance-form": "Mobile: Attendance Form",
  "mobile-attendance-edit": "Mobile: Edit Attendance",
  "mobile-leave-request-form": "Mobile: New Leave Request",
  "mobile-leave-detail": "Mobile: Leave Detail",
  "mobile-overtime-request": "Mobile: Overtime Request",
  "mobile-overtime-edit": "Mobile: Edit Overtime",
  "mobile-payslip": "Mobile: Payslip",
  "mobile-payslip-view-request": "Mobile: Payslip View Request",
  "mobile-payslip-view": "Mobile: Payslip View",
  "mobile-payslip-print-request": "Mobile: Payslip Print Request",
  "mobile-payslip-print-submitted": "Mobile: Payslip Print Submitted",
  "mobile-self-assessment": "Mobile: Self Assessment",
  "mobile-assessment-form": "Mobile: Assessment Form",
  "mobile-manager-assessment": "Mobile: Manager Assessment",
  "mobile-assessment-manager-form": "Mobile: Manager Assessment Form",
  "mobile-supervisor-assessment": "Mobile: Supervisor Assessment",
  "mobile-supervisor-assessment-detail": "Mobile: Supervisor Assessment Detail",
  "mobile-supervisor-assessment-form": "Mobile: Supervisor Assessment Form",
  "mobile-supervisor-assessment-schedule": "Mobile: Supervisor Assessment Schedule",
  "mobile-okr-list": "Mobile: OKR List",
  "mobile-okr": "Mobile: OKR Detail",
  "mobile-okr-key-result": "Mobile: OKR Key Result",
  "mobile-offboarding": "Mobile: Offboarding",
  "mobile-exit-form": "Mobile: Exit Form",
  "mobile-exit-schedule": "Mobile: Exit Interview Schedule",
  "mobile-work-handover": "Mobile: Work Handover",
  "mobile-document-handover": "Mobile: Document Handover",
  "mobile-responsibility-handover": "Mobile: Responsibility Handover"
}
