import z from "zod";

export const employeeManagementFormScheme = z.object({
  photo: z.string(),
  name: z.string().min(1, "required"),
  email: z.email().min(1, "required"),
  role: z.string().min(1, "required"),
  countryCode: z.string().min(1, "required"),
  phoneNumber: z.string().min(1, "required"),
  gender: z.enum(["male", "female"]),
  placeOfBirth: z.string().min(1, "required"),
  bornDate: z.date(),
  maritalStatus: z.enum([
    "single",
    "married",
    "divorced",
    "widowed",
    "separated",
  ]),
  bloodType: z.string().min(1, "required"),
  height: z.number().min(1, "required"),
  weight: z.number().min(1, "required"),
  idNumber: z.string().min(16, "required"),
  npwp: z.string().min(1, "required"),
  bpjs: z.string(),
  addressCitizen: z.string().min(1, "required"),
  residentalAddress: z.string().min(1, "required"),
  hobby: z.string().min(1, "required"),
  achievement: z.string().min(1, "required"),
  personalDescription: z.string().min(1, "required"),
  socialMediaOption: z.string().min(1, "required"),
  instagram: z.string().optional(),
  x: z.string().optional(),
  facebook: z.string().optional(),
  linkedin: z.string().optional(),
  other: z.string().optional(),
  position: z.string().min(1, "required"),
  department: z.string().min(1, "required"),
  jobLevel: z.string().min(1, "required"),
  primaryDirectReport: z.string().min(1, "required"),
  additionalDirectReport: z.string(),
  team: z.string(),
  startDate: z.date().min(1, "required"),
  endDate: z.date().min(1, "required"),
  status: z.string().min(1, "required"),
  baseSalary: z.number().min(1, "required"),
  nettSalary: z.number().min(1, "required"),
  allowanceType: z.string().min(1, "required"),
  allowanceValue: z.number().min(1, "required"),
  bank: z.string().min(1, "required"),
  bankAccountNumber: z.string().min(1, "required"),
  bankAccountName: z.string().min(1, "required"),
  families: {
    name: z.string().min(1, "required"),
    relationship: z.string().min(1, "required"),
    placeOfBirth: z.string().min(1, "required"),
    bornDate: z.date(),
    education: z.string().min(1, "required"),
    email: z.email(),
    phoneNumber: z.string(),
    occupation: z.string(),
    company: z.string(),
  },
  formalEducations: {
    school: z.string().min(1, "required"),
    city: z.string().min(1, "required"),
    major: z.string().min(1, "required"),
    startDate: z.date().min(1, "required"),
    graduateDate: z.date().min(1, "required"),
    gpa: z.number().min(1, "required"),
  },
  nonFormalEducations: {
    institution: z.string().min(1, "required"),
    location: z.string().min(1, "required"),
    notes: z.string().min(1, "required"),
    startDate: z.date().min(1, "required"),
    graduateDate: z.date().min(1, "required"),
  },
  experiences: {
    company: z.string().min(1, "required"),
    initialPosition: z.string().min(1, "required"),
    finalPosition: z.string().min(1, "required"),
    supervision: z.string().min(1, "required"),
    supervisorContact: z.string().min(1, "required"),
    companyAddress: z.string().min(1, "required"),
    joinDate: z.date().min(1, "required"),
    resignDate: z.date().min(1, "required"),
    lastSalary: z.number().min(1, "required"),
    reasonOfResign: z.string().min(1, "required"),
  },
  contactOfReference: {
    name: z.string().min(1, "required"),
    relationship: z.string().min(1, "required"),
    email: z.email(),
    phoneNumber: z.string(),
    occupation: z.string(),
    company: z.string(),
  },
  attachments: {
    cv: z.string().min(1, "required"),
    idCard: z.string().min(1, "required"),
    bankAccount: z.string().min(1, "required"),
    graduationCertificate: z.string().min(1, "required"),
    healthInsurance: z.string().min(1, "required"),
    others: z.string().min(1, "required"),
  },
});

export const employeeManagementFormDefaultValues = {
  photo: "",
  name: "",
  role: "",
  email: "",
  countryCode: "+62",
  phoneNumber: "",
  gender: "male" as const,
  placeOfBirth: "",
  bornDate: new Date(),
  maritalStatus: "single" as const,
  bloodType: "",
  height: 0,
  weight: 0,
  idNumber: "",
  npwp: "",
  bpjs: "",
  addressCitizen: "",
  residentalAddress: "",
  hobby: "",
  achievement: "",
  personalDescription: "",
  instagram: "",
  twitter: "",
  x: "",
  other: "",
  facebook: "",
  socialMediaOption: "instagram",
  position: "",
  department: "",
  jobLevel: "",
  primaryDirectReport: "",
  additionalDirectReport: "",
  team: "",
  startDate: new Date(),
  endDate: new Date(),
  status: "",
  baseSalary: 0,
  nettSalary: 0,
  allowanceType: "",
  allowanceValue: 0,
  bank: "",
  bankAccountNumber: "",
  bankAccountName: "",
  families: {
    name: "",
    relationship: "",
    placeOfBirth: "",
    bornDate: new Date(),
    education: "",
    email: "",
    phoneNumber: "",
    occupation: "",
    company: "",
  },
  formalEducations: {
    school: "",
    city: "",
    major: "",
    startDate: new Date(),
    graduateDate: new Date(),
    gpa: 0,
  },
  nonFormalEducations: {
    institution: "",
    location: "",
    notes: "",
    startDate: new Date(),
    graduateDate: new Date(),
  },
  experiences: {
    company: "",
    initialPosition: "",
    finalPosition: "",
    supervision: "",
    supervisorContact: "",
    companyAddress: "",
    joinDate: new Date(),
    resignDate: new Date(),
    lastSalary: 0,
    reasonOfResign: "",
  },
  contactOfReference: {
    name: "",
    relationship: "",
    email: "",
    phoneNumber: "",
    occupation: "",
    company: "",
  },
  attachments: {
    cv: "",
    idCard: "",
    bankAccount: "",
    graduationCertificate: "",
    healthInsurance: "",
    others: "",
  },
} as const;
