export default {
  "login": "Masuk",
  "reset-password": "Atur ulang kata sandi yang lupa",
  "change-password": "Ubah kata sandi (login pertama)",
  "dashboard-pending": "Lihat dan tindak lanjuti item tertunda",
  "dashboard-analytics": "Lihat analitik",
  "dashboard-offboarding": "Kelola offboarding dari dasbor",
  "add-employee": "Tambah karyawan",
  "edit-employee": "Edit karyawan",
  "view-employee": "Lihat profil karyawan",
  "org-structure": "Kelola struktur organisasi",
  "start-offboarding": "Mulai offboarding",
  "salary-adjustment": "Proses penyesuaian gaji",
  "record-attendance": "Catat kehadiran",
  "request-leave": "Ajukan cuti",
  "request-business-trip": "Ajukan perjalanan dinas",
  "edit-leave": "Edit atau batalkan permintaan cuti",
  "request-overtime": "Ajukan lembur",
  "approve-business-trip": "Setujui atau tolak perjalanan dinas",
  "approve-attendance": "Setujui atau tolak kehadiran/cuti",
  "view-payrun": "Lihat daftar dan detail payrun",
  "process-payrun": "Proses payrun",
  "payroll-access": "Minta akses payroll",
  "self-assessment": "Lengkapi penilaian diri",
  "supervisor-assessment": "Lengkapi penilaian atasan",
  "okr": "Buat atau perbarui OKR",
  "kpi": "Kelola KPI",
  "access-control": "Tambah atau edit akses pengguna",
  "company-profile": "Edit profil perusahaan",
  "attendance-config": "Konfigurasi pengaturan kehadiran",
  "leave-config": "Konfigurasi tipe cuti",
  "salary-config": "Konfigurasi komponen gaji",
  "ess-home": "Gunakan ESS sebagai karyawan"
}
